import tempfile
import os
import matplotlib
matplotlib.use('Agg')  # Headless mode for server environments
import matplotlib.pyplot as plt
from fpdf import FPDF
from services.grok_client import get_grok_client

# Define theme colors
BG_COLOR = (15, 23, 42)          # #0F172A
CARD_COLOR = (30, 41, 59)        # #1E293B
TEXT_PRIMARY = (226, 232, 240)   # #E2E8F0
TEXT_SECONDARY = (148, 163, 184) # #94A3B8
TEAL = (0, 212, 170)             # #00D4AA
RED = (255, 92, 106)             # #FF5C6A
YELLOW = (245, 197, 66)          # #F5C542
BAR_BG = (45, 55, 72)            # #2D3748

class DarkPDF(FPDF):
    def header(self):
        # Set dark background for the whole page
        self.set_fill_color(*BG_COLOR)
        self.rect(0, 0, 210, 297, style='F')
        
        # Header Logo/Title
        self.set_font('helvetica', 'B', 18)
        self.set_text_color(*TEAL)
        self.cell(10, 10, '> ', align='L')
        self.set_text_color(*TEXT_PRIMARY)
        self.cell(40, 10, 'ResumeIQ', align='L')
        
        self.set_font('helvetica', '', 10)
        self.set_text_color(*TEXT_SECONDARY)
        self.cell(0, 10, 'AI-Powered Resume Analyzer  -  Evaluation Report', align='R', new_x="LMARGIN", new_y="NEXT")
        
        # Separator line
        self.set_draw_color(*CARD_COLOR)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(*TEXT_SECONDARY)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by ResumeIQ', align='C')

def generate_donut_chart(score, path):
    fig, ax = plt.subplots(figsize=(2.5, 2.5), subplot_kw=dict(aspect="equal"))
    fig.patch.set_facecolor('#1E293B')
    ax.set_facecolor('#1E293B')
    
    vals = [score, 100-score]
    colors = ['#FF5C6A', '#2D3748']
    if score >= 80:
        colors[0] = '#00D4AA'
    elif score >= 60:
        colors[0] = '#F5C542'
    
    ax.pie(vals, colors=colors, startangle=90, counterclock=False, wedgeprops=dict(width=0.15))
    plt.text(0, 0, f"{score}%", ha='center', va='center', fontsize=24, fontweight='bold', color='#E2E8F0', fontfamily='sans-serif')
    
    plt.savefig(path, facecolor=fig.get_facecolor(), edgecolor='none', bbox_inches='tight', transparent=True, dpi=150)
    plt.close()

def generate_importance_text(job_description, missing_skills):
    if not missing_skills:
        return "You have no missing skills! You appear to be highly qualified for this role based on your resume."
    
    client = get_grok_client()
    skills_str = ", ".join(missing_skills)
    prompt = f"Job Description: {job_description}\n\nMissing Skills: {skills_str}\n\nPlease explain concisely why these specific missing skills are important for this role, and provide a brief suggestion for the candidate on how to bridge this gap. Format it as a short paragraph."
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "You are an expert career coach. Be concise and professional."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=400
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Could not generate explanation due to an API error: {e}"

def safe_text(text):
    return text.replace("’", "'").replace("“", '"').replace("”", '"').replace("–", "-").encode('latin-1', 'replace').decode('latin-1')

def generate_evaluation_pdf(data: dict) -> str:
    pdf = DarkPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    score = data.get('match_score', 0)
    matched = data.get("matched_skills", [])
    missing = data.get("missing_skills", [])
    total_skills = len(matched) + len(missing)
    if total_skills == 0: total_skills = 1
    
    temp_dir = tempfile.gettempdir()
    chart_path = os.path.join(temp_dir, "score_donut.png")
    generate_donut_chart(score, chart_path)

    # --- SCORE CARD ---
    pdf.set_fill_color(*CARD_COLOR)
    pdf.rect(10, 30, 190, 60, style='F')
    
    pdf.image(chart_path, x=15, y=35, w=50)
    
    pdf.set_xy(70, 40)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(*TEXT_PRIMARY)
    pdf.cell(0, 10, "Your Match Score", ln=1)
    
    pdf.set_xy(70, 50)
    pdf.set_font("helvetica", "", 11)
    if score >= 80:
        pdf.set_text_color(*TEAL)
        pdf.cell(5, 5, "> ")
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.cell(0, 5, "Excellent match - highly qualified")
    elif score >= 60:
        pdf.set_text_color(*YELLOW)
        pdf.cell(5, 5, "> ")
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.cell(0, 5, "Good match - a few gaps to address")
    else:
        pdf.set_text_color(*RED)
        pdf.cell(5, 5, "> ")
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.cell(0, 5, "Low match - significant skill gaps identified")
    
    # Progress Bars
    bar_x = 70
    bar_y_matched = 65
    bar_y_missing = 75
    bar_w = 110
    bar_h = 4
    
    # Matched Bar
    pdf.set_xy(70, bar_y_matched - 4)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*TEXT_SECONDARY)
    pdf.cell(20, 5, "Matched")
    pdf.set_xy(185, bar_y_matched - 4)
    pdf.cell(10, 5, str(len(matched)), align='R')
    
    pdf.set_fill_color(*BAR_BG)
    pdf.rect(bar_x, bar_y_matched, bar_w, bar_h, style='F')
    pdf.set_fill_color(*TEAL)
    pdf.rect(bar_x, bar_y_matched, bar_w * (len(matched)/total_skills), bar_h, style='F')
    
    # Missing Bar
    pdf.set_xy(70, bar_y_missing - 4)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*TEXT_SECONDARY)
    pdf.cell(20, 5, "Missing")
    pdf.set_xy(185, bar_y_missing - 4)
    pdf.cell(10, 5, str(len(missing)), align='R')
    
    pdf.set_fill_color(*BAR_BG)
    pdf.rect(bar_x, bar_y_missing, bar_w, bar_h, style='F')
    pdf.set_fill_color(*RED)
    pdf.rect(bar_x, bar_y_missing, bar_w * (len(missing)/total_skills), bar_h, style='F')

    pdf.set_y(100)

    # --- SKILLS BREAKDOWN ---
    pdf.set_fill_color(*CARD_COLOR)
    pdf.rect(10, 100, 190, 45, style='F')
    
    # Matched Skills
    pdf.set_xy(15, 105)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(*TEAL)
    pdf.cell(90, 8, "Matched Skills", ln=1)
    
    pdf.set_xy(15, 115)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(*TEXT_PRIMARY)
    if matched:
        pdf.multi_cell(85, 6, safe_text(", ".join(matched)))
    else:
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.cell(85, 6, "None matched")
        
    # Missing Skills
    pdf.set_xy(105, 105)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(*RED)
    pdf.cell(90, 8, "Missing Skills", ln=1)
    
    pdf.set_xy(105, 115)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(*TEXT_PRIMARY)
    if missing:
        pdf.multi_cell(85, 6, safe_text(", ".join(missing)))
    else:
        pdf.set_text_color(*TEAL)
        pdf.cell(85, 6, "No skill gaps detected!")

    current_y = max(pdf.get_y(), 150)
    
    # --- WHY THIS MATTERS ---
    pdf.set_y(current_y + 5)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(*TEXT_PRIMARY)
    pdf.cell(0, 10, "Why these missing skills matter", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(*TEXT_SECONDARY)
    importance_text = generate_importance_text(data.get("job_description", ""), missing)
    pdf.multi_cell(0, 6, safe_text(importance_text))
    pdf.ln(8)
    
    # --- RECOMMENDATIONS ---
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(*TEXT_PRIMARY)
    pdf.cell(0, 10, "Recommended Learning Resources", new_x="LMARGIN", new_y="NEXT")
    
    recs = data.get("recommendations", [])
    if recs:
        for rec in recs:
            pdf.set_font("helvetica", "B", 11)
            pdf.set_text_color(*TEXT_PRIMARY)
            pdf.cell(0, 6, safe_text(rec.get("title", "")), new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(*TEAL)
            pdf.cell(0, 5, safe_text(rec.get("platform", "")), new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("helvetica", "U", 10)
            pdf.set_text_color(100, 149, 237) # Cornflower Blue for links
            pdf.cell(0, 5, safe_text(rec.get("url", "")), link=rec.get("url", ""), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)
    else:
        pdf.set_font("helvetica", "", 11)
        pdf.set_text_color(*TEXT_SECONDARY)
        pdf.multi_cell(0, 6, "No specific recommendations needed.")
        
    pdf_path = os.path.join(temp_dir, "ResumeIQ_Evaluation_Report.pdf")
    pdf.output(pdf_path)
    return pdf_path
